set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

if(DEFINED ENV{VSINSTALLDIR})
  set(VCPKG_VISUAL_STUDIO_PATH "$ENV{VSINSTALLDIR}")
  string(REGEX REPLACE "[/\\\\]+$" "" VCPKG_VISUAL_STUDIO_PATH "${VCPKG_VISUAL_STUDIO_PATH}")
endif()

if(DEFINED ENV{VCToolsVersion})
  set(VCPKG_PLATFORM_TOOLSET_VERSION "$ENV{VCToolsVersion}")
endif()
